script:
  - "npm run test"

language: node_js

node_js:
  - "0.10.28"

before_script:
  - npm install bower
  - ./node_modules/bower/bin/bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
